### ISSUE TITLE
Error: no element found: line 1, column 0

### ISSUE THREAD

**Issue by seebi** [nsmgr8/vitra#3]
I get a screen these error lines ...
Is this a known issue?

Our trac is secured with https as well as with HTTP auth (if this is important)

**Comment by nsmgr8** [comment]
What is your python version inside vim? Did you configure HTTPS in your vim server config? Do you have any trac log?

This generally means that Trac XML-RPC got confused what to respond and sent empty response which the client could not parse.

Have you tried both HTTP and HTTPS?

**Comment by seebi** [comment]
- `vim --version` shows `-L/usr/lib/python2.7/config -lpython2.7` as linked library
- scheme is set to `https`
- rpcpath to `/path/to/login/xmlrpc`  (it is not installed on vhost root)
- browsertest: access to the `http://server/.../xmlrpc` URL does result in blank pages without http-auth
- browsertest: access to the `https://server/.../xmlrpc` URL does result in a 401 and HTTPauth request

trac log files are not available for me ...

**Comment by nsmgr8** [comment]
What version is Trac? If it is 0.12+, then rpc_path should be /path/to/login/rpc. /xmlrpc is for older Trac.

**Comment by seebi** [comment]
trac version is 0.12.2 and /path/to/login/rpc works fine in browser after http-auth
(got a Protocol reference documentation)

Installed API version : 1.1.2-r9970

**Comment by nsmgr8** [comment]
Also could you run this in vim command?

```
:python print trac.server.ticket.get(AN_EXISTING_TICKET_NUMBER)
```

What error do you get?

**Comment by seebi** [comment]
This error lines ...

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1471, in parse_response
    p.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 560, in close
    self._parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

maybe the request is send to the http URL not HTTPS?

**Comment by nsmgr8** [comment]
Did you upgrade/install vitra today? Was it working before or never worked?

If it's broken after upgrade/install today, then probably I know what happened. Otherwise I need to investigate it more.

Thanks for your patience and help.

**Comment by seebi** [comment]
On Thu, Jul 05, 2012 at 04:04:32AM -0700, M. Nasimul Haque wrote:

> Did you upgrade/install vitra today? Was it working before or never worked?

I installed it today and never used it before ...

> If it's broken after upgrade/install today, then probably I know what happened. Otherwise I need to investigate it more.
> 
> Thanks for your patience and help.

Thanks for YOUR patience :)

Best regards

Sebastian Tramp

**Comment by nsmgr8** [comment]
Please upgrade your vitra. I have made the change. Please let me know whether it worked.

**Comment by seebi** [comment]
I am now at 7b57d8c and see the content ... thank you :-)
