### ISSUE TITLE
can not save wiki pages

### ISSUE THREAD

**Issue by seebi** [nsmgr8/vitra#6]
I've tried to edit a (pure ascii) wiki page but got an error

```
E382: Kann nicht schreiben, 'buftype'-Option ist gesetzt
```

which means

```
E382: Ca not write, 'buftype'-option is set
```

Do I need to configure something?

**Comment by nsmgr8** [comment]
You cannot save it via :w. You need to use :TWSave.

**Comment by seebi** [comment]
ok, sorry for not reading the docs :)

However, I got an error
    Error: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
which is most likely related to issue #4
